### ISSUE TITLE
file SQL incompleto

### ISSUE THREAD

**Issue by fulcorno** [TdP-prove-finali/MaturoAlessandro#1]
Non riesco a valutare il progetto perché il file Database.sql è incompleto.
Infatti non contiene l'istruzione CREATE DATABASE (e questo non è un grande problema, lo creo a mano), ma soprattutto non contiene nessuna istruzione CREATE TABLE (e quindi tutte le INSERT falliscono perché non ci sono le tabelle e non sappiamo che struttura abbiano).
Dovresti ri-esportare il file SQL selezionando tutte le opzioni.

**Comment by AlessandroMaturo** [comment]
Buongiorno, ho inserito il database con le istruzioni di CREATE DATABASE e CREATE TABLE. 
Il file DatabaseDefinitivo.zip si trova dentro la sezione Database.

**Comment by fulcorno** [comment]
ok, ora funziona tutto
